FROM node:18

WORKDIR /usr/src/app
COPY package*.json ./
COPY ../../libs ./libs
COPY ../../.env .
COPY . .

RUN npm ci
RUN npm run build event

ENV NODE_ENV=production
CMD ["node", "dist/apps/event/main.js"]